@startsalt

{#
    Workouts
    {
        Two minute workout
        Achilles
        Full body
        Cardio
        Archery
        Standing abs
        Airborne
        Legs super series
        Iron Man
    }
}

@endsalt
